name: ci

env:
  APP: "nba-data-api"

on:
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "**/README.md"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Clean Docker cache
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build the Docker image
        run: docker build --platform linux/arm64 --tag ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:latest .
